# Generated by Django 5.2.3 on 2025-09-30 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('due_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('due_status', models.CharField(choices=[('upcoming', 'Upcoming'), ('due_today', 'Due Today'), ('overdue', 'Overdue'), ('done', 'Done')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_bills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
