# Generated by Django 5.2.3 on 2025-10-17 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
        ('units', '0008_assignedunit_unit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybill',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_unit', to='units.unit'),
        ),
    ]
