# Generated by Django 5.2.3 on 2025-11-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_monthlybill_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybill',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
