# Generated by Django 5.2.3 on 2025-12-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_monthlybill_sms_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybill',
            name='construction_bond',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Construction bond amount for unit reconstruction/renovation', max_digits=10),
        ),
    ]
