# Generated by Django 5.2.3 on 2025-08-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
        ('units', '0004_alter_assignedunit_assigned_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='target_audience',
        ),
        migrations.AddField(
            model_name='notice',
            name='target_audience',
            field=models.ManyToManyField(blank=True, to='units.assignedunit'),
        ),
    ]
