# Generated by Django 5.2.3 on 2025-08-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_remove_notice_target_audience_notice_target_audience'),
        ('units', '0004_alter_assignedunit_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='target_audience',
            field=models.ManyToManyField(blank=True, to='units.unit'),
        ),
    ]
