# Generated by Django 5.2.3 on 2025-08-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_alter_notice_target_audience'),
        ('units', '0004_alter_assignedunit_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='target_audience',
            field=models.ManyToManyField(blank=True, related_name='notices', to='units.unit'),
        ),
    ]
