# Generated by Django 5.2.3 on 2025-10-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_alter_notice_target_audience'),
        ('units', '0008_assignedunit_unit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='target_audience',
            field=models.ManyToManyField(blank=True, related_name='notices', to='units.assignedunit'),
        ),
    ]
