# Generated by Django 5.2.3 on 2025-08-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='type',
            field=models.CharField(choices=[('complaint', 'Complaint'), ('question', 'Question'), ('request', 'Request')], default='request', max_length=20),
        ),
    ]
