# Generated by Django 5.2.3 on 2025-08-25 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='inquiries.inquirytype'),
        ),
    ]
