# Generated by Django 5.2.3 on 2025-08-25 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_alter_inquiry_inquiry_type'),
        ('units', '0004_alter_assignedunit_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='units.unit'),
        ),
    ]
