# Generated by Django 5.2.3 on 2025-12-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_alter_inquiry_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional photo attachment for the inquiry', null=True, upload_to='inquiries/'),
        ),
    ]
