# Generated by Django 5.2.3 on 2025-12-03 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0009_paymentmethod_account_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_format', models.TextField(blank=True, help_text='Format for payment references (e.g., Unit No. + Month)')),
                ('emergency_hotline', models.CharField(blank=True, help_text='Main emergency hotline', max_length=20)),
                ('security_guard_contact', models.CharField(blank=True, help_text='Security guard contact number', max_length=20)),
                ('fire_department', models.CharField(blank=True, help_text='Fire department contact', max_length=20)),
                ('police_station', models.CharField(blank=True, help_text='Local police station contact', max_length=20)),
                ('hospital', models.CharField(blank=True, help_text='Nearest hospital contact', max_length=20)),
                ('hoa_office_phone', models.CharField(blank=True, help_text='HOA office phone number', max_length=20)),
                ('hoa_email', models.EmailField(blank=True, help_text='HOA office email address', max_length=254)),
                ('office_hours', models.CharField(blank=True, help_text='Office operating hours', max_length=100)),
                ('office_address', models.TextField(blank=True, help_text='HOA office physical address')),
                ('maintenance_contact', models.CharField(blank=True, help_text='Maintenance department contact', max_length=20)),
                ('electrician_contact', models.CharField(blank=True, help_text='Electrician contact', max_length=20)),
                ('plumber_contact', models.CharField(blank=True, help_text='Plumber contact', max_length=20)),
                ('important_notices', models.TextField(blank=True, help_text='Important notices or announcements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_payment_methods', models.ManyToManyField(blank=True, help_text='Additional accepted payment methods', related_name='additional_for_hoa', to='payments.paymentmethod')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hoa_info', to=settings.AUTH_USER_MODEL)),
                ('primary_payment_method', models.ForeignKey(blank=True, help_text='Primary payment method for HOA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_hoa', to='payments.paymentmethod')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_hoa_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HOA Information',
                'verbose_name_plural': 'HOA Information',
                'ordering': ['-updated_at'],
            },
        ),
    ]
