# Generated by Django 5.2.3 on 2025-07-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedunit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
