# Generated by Django 5.2.3 on 2025-07-24 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_alter_assignedunit_deleted_at_alter_unit_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedunit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_units_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignedunit',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_units_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignedunit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_units_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
