# Generated by Django 5.2.3 on 2025-09-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_alter_assignedunit_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
