# Generated by Django 5.2.3 on 2025-10-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_alter_assignedunit_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedunit',
            name='amenities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignedunit',
            name='building',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedunit',
            name='maintenance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignedunit',
            name='security',
            field=models.BooleanField(default=True),
        ),
    ]
