# Generated by Django 5.2.3 on 2025-10-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_assignedunit_amenities_assignedunit_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedunit',
            name='unit_status',
            field=models.CharField(choices=[('owner_occupied', 'Owner Occupied'), ('rented_short_term', 'Rented Short Term'), ('air_bnb', 'Air Bnb')], default='owner_occupied', max_length=20),
        ),
    ]
