# Generated by Django 5.2.3 on 2025-10-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0008_assignedunit_unit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
