# Generated by Django 5.2.3 on 2025-10-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_unit_isavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedunit',
            name='move_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
