# Generated by Django 5.2.3 on 2025-11-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0010_assignedunit_move_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='building',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
