# Generated by Django 5.2.3 on 2025-11-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0011_unit_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='bedroom',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
