# Generated by Django 5.2.3 on 2025-11-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0012_unit_bedroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='bedroom',
            new_name='bedrooms',
        ),
        migrations.AlterField(
            model_name='assignedunit',
            name='amenities',
            field=models.BooleanField(default=True),
        ),
    ]
