# Generated by Django 5.2.3 on 2025-11-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0013_rename_bedroom_unit_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
    ]
