# Generated by Django 5.2.3 on 2025-11-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0014_alter_unit_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='floor_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
