# Generated by Django 5.2.3 on 2025-08-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
