# Generated by Django 5.2.3 on 2025-10-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymentrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
