# Generated by Django 5.2.3 on 2025-10-03 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentrecord_reference_number'),
        ('units', '0005_unit_rent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='units.unit'),
        ),
    ]
