# Generated by Django 5.2.3 on 2025-10-10 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
        ('payments', '0006_paymentrecord_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.monthlybill'),
        ),
    ]
