# Generated by Django 5.2.3 on 2025-11-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentrecord_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='advance_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='advance_months_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='advance_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='is_advance_allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_type',
            field=models.CharField(choices=[('regular', 'Regular Payment'), ('advance', 'Advance Payment')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
